[theme]
primaryColor = "#8b5cf6"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[server]
headless = true
enableXsrfProtection = false
enableCORS = true
